"""
Seed data for standardised exercise definitions.
"""
from typing import Final

STANDARDISED_EXERCISE_DEFINITIONS: Final[list[dict[str, str]]] = [
    {"exercise_name": "Barbell Back Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Front Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Goblet Squat", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bulgarian Split Squat", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Walking Lunges", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Reverse Lunges", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Leg Press", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Hack Squat", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Romanian Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Stiff Leg Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Good Morning", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Hip Thrust", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Glute Bridge", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Leg Extension", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Seated Leg Curl", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Lying Leg Curl", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Nordic Hamstring Curl", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Standing Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Seated Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Donkey Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Incline Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Decline Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Incline Dumbbell Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Decline Dumbbell Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Machine Chest Press", "primary_muscle_group": "Chest", "equipment_required": "Machine"},
    {"exercise_name": "Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Paused Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Chest Dip", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Pec Deck Fly", "primary_muscle_group": "Chest", "equipment_required": "Machine"},
    {"exercise_name": "Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "Low to High Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "High to Low Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell Fly", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Svend Press", "primary_muscle_group": "Chest", "equipment_required": "Plate"},
    {"exercise_name": "Pullover", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Landmine Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Single Arm Landmine Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Conventional Deadlift", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Sumo Deadlift", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Barbell Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Pendlay Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "T Bar Row", "primary_muscle_group": "Back", "equipment_required": "Machine"},
    {"exercise_name": "Dumbbell Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "Chest Supported Row", "primary_muscle_group": "Back", "equipment_required": "Machine"},
    {"exercise_name": "Seated Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Close Grip Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Wide Grip Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Wide Grip Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Neutral Grip Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Single Arm Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Pull Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Chin Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Pull Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Straight Arm Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Face Pull", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Barbell Overhead Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Seated Barbell Overhead Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Shoulder Press", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Arnold Press", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Machine Shoulder Press", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Cable Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Machine Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Rear Delt Fly", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Reverse Pec Deck", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Cable Rear Delt Fly", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Front Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Upright Row", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Upright Row", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Y Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Barbell Shrug", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Shrug", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Farmer Carry", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Scaption Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Barbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "EZ Bar Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Alternating Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Incline Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Hammer Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Preacher Curl", "primary_muscle_group": "Biceps", "equipment_required": "Machine"},
    {"exercise_name": "Cable Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Rope Hammer Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Concentration Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Spider Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bayesian Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Close Grip Bench Press", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Skull Crusher", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Overhead Triceps Extension", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Single Arm Overhead Triceps Extension", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Cable Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Rope Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Reverse Grip Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell Kickback", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bench Dip", "primary_muscle_group": "Triceps", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Dip", "primary_muscle_group": "Triceps", "equipment_required": "Bodyweight"},
    {"exercise_name": "Machine Dip", "primary_muscle_group": "Triceps", "equipment_required": "Machine"},
    {"exercise_name": "Pallof Press", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Cable Crunch", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Hanging Leg Raise", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Ab Wheel Rollout", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Plank", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Side Plank", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Russian Twist", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Dead Bug", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Bird Dog", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Back Extension", "primary_muscle_group": "Core", "equipment_required": "Machine"},
    {"exercise_name": "Zercher Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Box Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Pause Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Goblet Split Squat", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Deficit Romanian Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Single Leg Leg Press", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Sissy Squat", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Step Up", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Lateral Lunge", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Curtsy Lunge", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Adductor Machine", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Abductor Machine", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Cable Pull Through", "primary_muscle_group": "Legs", "equipment_required": "Cable"},
    {"exercise_name": "B-Stance Romanian Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Glute Ham Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Spoto Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Floor Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Larsen Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Guillotine Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Floor Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Squeeze Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Diamond Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Archer Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Decline Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Incline Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Single Arm Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "Deficit Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Rack Pull", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Snatch Grip Deadlift", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Meadows Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Kroc Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "Seal Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Incline Dumbbell Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "Renegade Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "V-Bar Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Behind the Neck Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Hammer Strength Row", "primary_muscle_group": "Back", "equipment_required": "Machine"},
    {"exercise_name": "Inverse Row", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Single Arm Dumbbell Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "Hyperextension", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Superman", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Z-Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Push Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Single Arm Dumbbell Press", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bradford Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Lu Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Plate"},
    {"exercise_name": "Chest Supported Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Single Arm Cable Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Rear Delt Row", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Lying Rear Delt Fly", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Face Pull with External Rotation", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Plate Front Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Plate"},
    {"exercise_name": "Single Arm Cable Front Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell High Pull", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Snatch Grip Shrug", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Drag Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Cheat Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Zottman Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Waiters Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Single Arm Cable Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "High Cable Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Strict Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Reverse Barbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Reverse EZ Bar Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "JM Press", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Board Press", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Tate Press", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Katana Extension", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Cross Body Cable Extension", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Single Arm Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell Overhead Extension", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bodyweight Extension", "primary_muscle_group": "Triceps", "equipment_required": "Bodyweight"},
    {"exercise_name": "Dragon Flag", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "L-Sit", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Hollow Body Hold", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "V-Up", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Bicycle Crunch", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Toes to Bar", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Windshield Wiper", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Woodchopper", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Weighted Plank", "primary_muscle_group": "Core", "equipment_required": "Plate"},
    {"exercise_name": "Suitcase Carry", "primary_muscle_group": "Core", "equipment_required": "Dumbbell"},
    {"exercise_name": "Kneeling Cable Crunch", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Reverse Crunch", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Clean and Jerk", "primary_muscle_group": "Full Body", "equipment_required": "Barbell"},
    {"exercise_name": "Snatch", "primary_muscle_group": "Full Body", "equipment_required": "Barbell"},
    {"exercise_name": "Power Clean", "primary_muscle_group": "Full Body", "equipment_required": "Barbell"},
    {"exercise_name": "Hang Clean", "primary_muscle_group": "Full Body", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Snatch", "primary_muscle_group": "Full Body", "equipment_required": "Dumbbell"},
    {"exercise_name": "Kettlebell Swing", "primary_muscle_group": "Full Body", "equipment_required": "Kettlebell"},
    {"exercise_name": "Turkish Get Up", "primary_muscle_group": "Full Body", "equipment_required": "Kettlebell"},
    {"exercise_name": "Burpee", "primary_muscle_group": "Full Body", "equipment_required": "Bodyweight"},
    {"exercise_name": "Box Jump", "primary_muscle_group": "Full Body", "equipment_required": "Bodyweight"},
    {"exercise_name": "Thruster", "primary_muscle_group": "Full Body", "equipment_required": "Barbell"},
    {"exercise_name": "Wall Ball", "primary_muscle_group": "Full Body", "equipment_required": "Medicine Ball"},
    {"exercise_name": "Sled Push", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Sled Pull", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Farmer's Walk", "primary_muscle_group": "Full Body", "equipment_required": "Dumbbell"},
    {"exercise_name": "Atlas Stone Lift", "primary_muscle_group": "Full Body", "equipment_required": "Stone"},
    {"exercise_name": "Tire Flip", "primary_muscle_group": "Full Body", "equipment_required": "Tire"},
    {"exercise_name": "Sledgehammer Swing", "primary_muscle_group": "Full Body", "equipment_required": "Sledgehammer"},
    {"exercise_name": "Battle Ropes", "primary_muscle_group": "Full Body", "equipment_required": "Battle Ropes"},
    {"exercise_name": "Prowler Push", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Prowler Pull", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Sled Drag", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Sled Row", "primary_muscle_group": "Full Body", "equipment_required": "Machine"},
    {"exercise_name": "Kettlebell Clean", "primary_muscle_group": "Full Body", "equipment_required": "Kettlebell"}
]
