"""
Seed data for standardised exercise definitions.
"""
from typing import Final

STANDARDISED_EXERCISE_DEFINITIONS: Final[list[dict[str, str]]] = [
    {"exercise_name": "Barbell Back Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Front Squat", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Goblet Squat", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bulgarian Split Squat", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Walking Lunges", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Reverse Lunges", "primary_muscle_group": "Legs", "equipment_required": "Dumbbell"},
    {"exercise_name": "Leg Press", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Hack Squat", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Romanian Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Stiff Leg Deadlift", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Good Morning", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Hip Thrust", "primary_muscle_group": "Legs", "equipment_required": "Barbell"},
    {"exercise_name": "Glute Bridge", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Leg Extension", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Seated Leg Curl", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Lying Leg Curl", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Nordic Hamstring Curl", "primary_muscle_group": "Legs", "equipment_required": "Bodyweight"},
    {"exercise_name": "Standing Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Seated Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Donkey Calf Raise", "primary_muscle_group": "Legs", "equipment_required": "Machine"},
    {"exercise_name": "Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Incline Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Decline Barbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Bench Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Incline Dumbbell Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Decline Dumbbell Press", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Machine Chest Press", "primary_muscle_group": "Chest", "equipment_required": "Machine"},
    {"exercise_name": "Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Paused Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Push Up", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Chest Dip", "primary_muscle_group": "Chest", "equipment_required": "Bodyweight"},
    {"exercise_name": "Pec Deck Fly", "primary_muscle_group": "Chest", "equipment_required": "Machine"},
    {"exercise_name": "Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "Low to High Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "High to Low Cable Fly", "primary_muscle_group": "Chest", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell Fly", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Svend Press", "primary_muscle_group": "Chest", "equipment_required": "Plate"},
    {"exercise_name": "Pullover", "primary_muscle_group": "Chest", "equipment_required": "Dumbbell"},
    {"exercise_name": "Landmine Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Single Arm Landmine Press", "primary_muscle_group": "Chest", "equipment_required": "Barbell"},
    {"exercise_name": "Conventional Deadlift", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Sumo Deadlift", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Barbell Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "Pendlay Row", "primary_muscle_group": "Back", "equipment_required": "Barbell"},
    {"exercise_name": "T Bar Row", "primary_muscle_group": "Back", "equipment_required": "Machine"},
    {"exercise_name": "Dumbbell Row", "primary_muscle_group": "Back", "equipment_required": "Dumbbell"},
    {"exercise_name": "Chest Supported Row", "primary_muscle_group": "Back", "equipment_required": "Machine"},
    {"exercise_name": "Seated Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Close Grip Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Wide Grip Cable Row", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Wide Grip Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Neutral Grip Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Single Arm Lat Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Pull Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Chin Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Pull Up", "primary_muscle_group": "Back", "equipment_required": "Bodyweight"},
    {"exercise_name": "Straight Arm Pulldown", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Face Pull", "primary_muscle_group": "Back", "equipment_required": "Cable"},
    {"exercise_name": "Barbell Overhead Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Seated Barbell Overhead Press", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Shoulder Press", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Arnold Press", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Machine Shoulder Press", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Cable Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Machine Lateral Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Rear Delt Fly", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Reverse Pec Deck", "primary_muscle_group": "Shoulders", "equipment_required": "Machine"},
    {"exercise_name": "Cable Rear Delt Fly", "primary_muscle_group": "Shoulders", "equipment_required": "Cable"},
    {"exercise_name": "Front Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Upright Row", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Upright Row", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Y Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Barbell Shrug", "primary_muscle_group": "Shoulders", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Shrug", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Farmer Carry", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Scaption Raise", "primary_muscle_group": "Shoulders", "equipment_required": "Dumbbell"},
    {"exercise_name": "Barbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "EZ Bar Curl", "primary_muscle_group": "Biceps", "equipment_required": "Barbell"},
    {"exercise_name": "Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Alternating Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Incline Dumbbell Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Hammer Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Preacher Curl", "primary_muscle_group": "Biceps", "equipment_required": "Machine"},
    {"exercise_name": "Cable Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Rope Hammer Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Concentration Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Spider Curl", "primary_muscle_group": "Biceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bayesian Curl", "primary_muscle_group": "Biceps", "equipment_required": "Cable"},
    {"exercise_name": "Close Grip Bench Press", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Skull Crusher", "primary_muscle_group": "Triceps", "equipment_required": "Barbell"},
    {"exercise_name": "Overhead Triceps Extension", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Single Arm Overhead Triceps Extension", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Cable Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Rope Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Reverse Grip Triceps Pushdown", "primary_muscle_group": "Triceps", "equipment_required": "Cable"},
    {"exercise_name": "Dumbbell Kickback", "primary_muscle_group": "Triceps", "equipment_required": "Dumbbell"},
    {"exercise_name": "Bench Dip", "primary_muscle_group": "Triceps", "equipment_required": "Bodyweight"},
    {"exercise_name": "Weighted Dip", "primary_muscle_group": "Triceps", "equipment_required": "Bodyweight"},
    {"exercise_name": "Machine Dip", "primary_muscle_group": "Triceps", "equipment_required": "Machine"},
    {"exercise_name": "Pallof Press", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Cable Crunch", "primary_muscle_group": "Core", "equipment_required": "Cable"},
    {"exercise_name": "Hanging Leg Raise", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Ab Wheel Rollout", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Plank", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Side Plank", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Russian Twist", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Dead Bug", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Bird Dog", "primary_muscle_group": "Core", "equipment_required": "Bodyweight"},
    {"exercise_name": "Back Extension", "primary_muscle_group": "Core", "equipment_required": "Machine"},
]
